title: Geoinformatiikan menetelmät
description: Tässä blogissa jaan edistymistäni ja oivalluksiani Geoinformatiikan menetelmät -kurssilla.
author: "Eemeli Ingervo"

theme: minima

base_url: /geoinformatiikan-menetelmat

# Minima social links
github_username: Jeemlei
linkedin_username: gervo

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
